name: Deploy Front
'on': push
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./front/site-app && npm ci && npm run build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SKILL_LEARN }}'
          projectId: skill-learn
          entryPoint: "./front/site-app"
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
